# File system
alias ls='eza -lh --group-directories-first --icons=auto --color=auto'
alias lsa='ls -a'
alias lt='eza --tree --level=2 --long --icons --git --color=auto'
alias lta='lt -a'
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
alias find='fd -H --color=always'
alias cd='z'
alias grep='rg --color=auto'

# Directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Tools
alias n='nvim'
alias g='git'
alias d='docker'
alias r='rails'
alias lzg='lazygit'
alias lzd='lazydocker'
alias vim='nvim'
alias cat='bat'
alias man='wikiman'

# Git
alias gcm='git commit -m'
alias gcam='git commit -a -m'
alias gcad='git commit -a --amend'

# FastFetch
# alias fastfetch='fastfetch --logo Blackarch --logo-color-1 blue --logo-color-2 blue --logo-color-3 red'

# Compression
compress() { tar -czf "${1%/}.tar.gz" "${1%/}"; }
alias decompress="tar -xzf"

# Convert webm files generated by the Gnome screenshot video recorder to mp4s that are more compatible
webm2mp4() {
  input_file="$1"
  output_file="${input_file%.webm}.mp4"
  ffmpeg -i "$input_file" -c:v libx264 -preset slow -crf 22 -c:a aac -b:a 192k "$output_file"
}

# Custom
alias on="~/shell/scripts/obsidian/new-note.sh"
alias setup_font="~/shell/scripts/setup/setup_font.sh"
alias setup_arch="~/shell/scripts/setup/setup_arch.sh"
alias setup_firmware="~/shell/scripts/setup/setup_firmware.sh"
alias setup_emacs="~/shell/scripts/setup/setup_emacs.sh"
alias doom="~/.emacs.d/bin/doom"
