source "$HOME"/shell/aliases.sh
source "$HOME"/shell/env.sh
source "$HOME"/shell/functions.sh
source "$HOME"/shell/zsh/aliases.sh
source "$HOME"/shell/zsh/hooks.sh
source "$HOME"/shell/zsh/init.sh
source "$HOME"/shell/zsh/keybinds.sh
source "$HOME"/shell/zsh/options.sh
source "$HOME"/shell/zsh/plugins.sh
source "$HOME"/shell/zsh/shell.sh
