general.import = ["~/.config/omarchy/current/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "zellij"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 10.5

[window]
padding.x = 12
padding.y = 12
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
