[env]
TERM = "xterm-256color"

[terminal.shell]
program = "zellij"

[window]
decorations = "none"
padding = { x = 12, y = 12 }
opacity = 0.90
blur = true
startup_mode = "Maximized"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[font]
normal = { family = "Monaspace Neon Var", style = "Regular" }
bold = { family = "Monaspace Neon Var", style = "Bold" }
italic = { family = "Monaspace Neon Var", style = "Italic" }
bold_italic = { family = "Monaspace Neon Var", style = "Bold Italic" }
size = 11
offset = { x = 0, y = 0 }
glyph_offset = { x = 1, y = 1 }

[scrolling]
history = 5000

# Catppuccin Themes

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml",
]
