"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """
[░▒▓](bright-red)\
$os\
$username\
[](bg:bright-blue fg:bright-red)\
$directory\
[](bg:bright-yellow fg:bright-blue)\
$git_branch\
$git_status\
[](fg:bright-yellow bg:bright-green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](bright-green)\
$line_break\
$character
"""

right_format = """[](white)\
$cmd_duration\
[](fg:bright-blue bg:white)\
$time[▓▒░](bright-blue)
"""
# palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:bright-red fg:black"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:bright-red fg:black"
style_root = "bg:bright-red fg:black"
format = '[ $user]($style)'

[directory]
style = "bg:bright-blue fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Projects" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:bright-yellow"
format = '[[ $symbol $branch ](fg:black bg:bright-yellow)]($style)'

[git_status]
style = "bg:bright-yellow"
format = '[[($all_status$ahead_behind )](fg:black bg:bright-yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:bright-green"
format = '[[ $symbol( $version) ](fg:black bg:bright-green)]($style)'

[c]
symbol = " "
style = "bg:bright-green"
format = '[[ $symbol( $version) ](fg:black bg:bright-green)]($style)'

[rust]
symbol = ""
style = "bg:bright-green"
format = '[[ $symbol( $version) ](fg:black bg:bright-green)]($style)'

[golang]
symbol = ""
style = "bg:bright-green"
format = '[[ $symbol( $version) ](fg:black bg:bright-green)]($style)'

[php]
symbol = ""
style = "bg:bright-green"
format = '[[ $symbol( $version) ](fg:black bg:bright-green)]($style)'

[java]
symbol = " "
style = "bg:bright-green"
format = '[[ $symbol( $version) ](fg:black bg:bright-green)]($style)'

[kotlin]
symbol = ""
style = "bg:bright-green"
format = '[[ $symbol( $version) ](fg:black bg:bright-green)]($style)'

[haskell]
symbol = ""
style = "bg:bright-green"
format = '[[ $symbol( $version) ](fg:black bg:bright-green)]($style)'

[python]
symbol = ""
style = "bg:bright-green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:black bg:bright-green)]($style)'

[docker_context]
symbol = ""
style = "bg:white"
format = '[[ $symbol( $context) ](fg:black bg:white)]($style)'

[conda]
symbol = "  "
style = "fg:black bg:white"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:bright-blue"
format = '[[  $time ](fg:black bg:bright-blue)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:bright-green)'
error_symbol = '[❯](bold fg:bright-red)'
vimcmd_symbol = '[❮](bold fg:bright-green)'
vimcmd_replace_one_symbol = '[❮](bold fg:bright-blue)'
vimcmd_replace_symbol = '[❮](bold fg:bright-blue)'
vimcmd_visual_symbol = '[❮](bold fg:bright-yellow)'

[cmd_duration]
show_milliseconds = false
format = "[[  in $duration ](fg:black bg:white)]($style)"
style = "bg:bright-blue"
disabled = false
show_notifications = false
min_time_to_notify = 45000
