[tools]
go = "latest"
node = "lts"
rust = "latest"
ruby = "latest"
deno = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

# [settings.ruby]
# ruby_build_opts = "CC=gcc-14 CXX=g++-14"
